In [1]:
import numpy as np

array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(array_1d)

print("Shape:", array_1d.shape)

1D Array:
[10 20 30 40 50]
Shape: (5,)


In [2]:
import numpy as np

array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(array_1d)

print("Shape:", array_1d.shape)

1D Array:
[10 20 30 40 50]
Shape: (5,)


In [3]:
array_2d = np.array([
    [1,2,3],
    [4,5,6]
])

print(array_2d)

print("Shape:", array_2d.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [4]:
numbers = np.array([1,2,3,4,5])

result = numbers + 10

print(result)

[11 12 13 14 15]


In [5]:
a = np.array([1,2,3,4])

b = np.array([5,6,7,8])

print("Addition:", a+b)

print("Subtraction:", a-b)

print("Multiplication:", a*b)

print("Division:", a/b)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [6]:
import pandas as pd

data = {
    "Student": ["Asha","Rahul","Priya","Kiran","Anil"],
    "Math": [85,78,92,88,76],
    "Science": [90,82,95,84,80],
    "English": [75,80,88,90,70]
}

df = pd.DataFrame(data)

df.to_csv("student_marks.csv", index=False)

print(df)

  Student  Math  Science  English
0    Asha    85       90       75
1   Rahul    78       82       80
2   Priya    92       95       88
3   Kiran    88       84       90
4    Anil    76       80       70


In [8]:
math_scores = df["Math"]

print("Mean:", np.mean(math_scores))

Mean: 83.8


In [9]:
print("Standard Deviation:", np.std(math_scores))

Standard Deviation: 6.013318551349164


In [10]:
correlation = df["Math"].corr(df["Science"])

print("Correlation between Math and Science:", correlation)

Correlation between Math and Science: 0.8435039553927924
